# Generated by Django 3.1 on 2020-08-27 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restfulapi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='owner',
        ),
    ]
